image:
  file: .gitpod.dockerfile

ports:
  - port: 80
    onOpen: open-preview
  - port: 3306
    onOpen: ignore

tasks:
  - name: Apache & MySQL
    command: |
      sudo service mysql start
      sudo apache2ctl start
      echo "Apache and MySQL are running. You can access phpMyAdmin at '/phpmyadmin'"
